# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
pool:
  vmImage: 'ubuntu-latest'
variables:
  suscription: 'ConnectionCrud'
  RG: 'yaml-RG'
  AppService: 'AppServiceyml'
  Location: westus2
  Clave: M4ndr4k3*346
  DBUSER: dbadmin
  MySQL: myyamldbdeploy
  DBName: crud_app
  rootFolder: $(System.DefaultWorkingDirectory)
  appname: CrudLabWebApp
stages:
- stage: Build
  displayName: Build stage
  variables:
    phpVersion: '7.3'
  jobs:
  - job: BuildJob
    steps:    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: 'code'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'WebApp'
        publishLocation: 'Container'

- stage: InfraPre
  jobs:
  - job: Setup_RG_AppSvC
    displayName: Setup RG and App Service
    steps:
    - checkout: none
    - task: AzureCLI@2
      displayName: 'Create RG and App Service'
      inputs:
        azureSubscription: $(suscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create -n $(RG) -l $(Location)
          az appservice plan create -g $(RG) -n $(AppService) --sku FREE --is-linux
- stage: InfraDeploy
  jobs:
  - job: CreateMySQL
    displayName: Create the MySQL
    steps:
    - task: AzureResourceManagerTemplateDeployment@3
      inputs:
        deploymentScope: 'Resource Group'
        azureResourceManagerConnection: $(suscription)
        subscriptionId: '8bcb5781-f38f-411c-9b22-34c1e8b45c83'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(RG)
        location: $(Location)
        templateLocation: 'URL of the file'
        csmFileLink: 'https://raw.githubusercontent.com/jmartinperalta/crud/master/mysql/template.json'
        deploymentMode: 'Incremental'
    - task: AzureCLI@1
      displayName: 'Azure CLI '
      inputs:
        azureSubscription: $(suscription)
        scriptLocation: inlineScript
        inlineScript: |
            az mysql server firewall-rule create --resource-group $(RG) --server $(MySQL) --name "AllowAllWindowsAzureIps" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
            az mysql server update --resource-group $(RG) --name $(MySQL) --ssl-enforcement Disabled
    - task: MysqlDeploymentOnMachineGroup@1
      inputs:
        TaskNameSelector: 'InlineSqlTask'
        SqlInline: |
          SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
          SET AUTOCOMMIT = 0;
          START TRANSACTION;
          CREATE TABLE `users` (
            `id` int(11) UNSIGNED NOT NULL,
            `username` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
            `user_email` varchar(191) COLLATE utf8mb4_unicode_ci NOT NULL
          ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
          
          ALTER TABLE `users`
            ADD PRIMARY KEY (`id`),
            ADD UNIQUE KEY `user_email` (`user_email`);
          
          ALTER TABLE `users`
            MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT;
          COMMIT;
        ServerName: '$(MySQL).mysql.database.azure.com'
        DatabaseName: '$(DBName)'
        SqlUsername: '$(DBUSER)@$(MySQL)'
        SqlPassword: '$(Clave)'

- stage: ConfigWeb
  jobs:
  - job: WebAppConfiguration
    displayName: Deploy WebApp
    steps:
    - task: AzureCLI@1
      inputs:
        azureSubscription: $(suscription)
        scriptLocation: 'inlineScript'
        inlineScript: |
                  az webapp create -g $(RG) -p $(AppService) -n $(appname) --runtime "PHP|7.3"
                  az webapp config appsettings set -g $(RG) -n $(appname) --settings WEBSITES_PORT=80
                  az webapp config connection-string set -g $(RG) -n $(appname) -t MySql --settings HOST=$(MySQL).mysql.database.azure.com USER=$(DBUSER)@$(MySQL) PASSWORD=$(Clave)
                  az webapp start -g $(RG) -n $(appname)
    - task: DownloadPipelineArtifact@2
      inputs:
          buildType: 'current'
          targetPath: '$(Build.ArtifactStagingDirectory)'
    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Artifact'
      inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: $(suscription)
          appType: 'webAppLinux'
          WebAppName: $(appname)
          packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
          RuntimeStack: 'PHP|7.3'