# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  suscription: 'Suscripción de Visual Studio Professional (8bcb5781-f38f-411c-9b22-34c1e8b45c83)'
  RG: 'yaml-RG'
  AppService: 'AppServiceyml'
  Location: westus2

stages:
- stage: InfraPre
  jobs:
  - job: Setup_RG_AppSvC
    displayName: Setup RG and App Service
    steps:
    - checkout: none
    - task: AzureCLI@2
      displayName: 'Create RG and App Service'
      inputs:
        azureSubscription: $(suscription)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az group create -n $(RG) -l $(Location)
          az appservice plan create -g $(RG) -n $(AppService) --sku B1 --is-linux
- stage: InfraDeploy
  jobs:
  - job: CreateWebApp_MySQL
    displayName: Create the WebApp and MySQL
    steps:
      - task: AzureResourceGroupDeployment@2
        displayName: 'Azure Deployment: ARM MySQL'
        inputs:
          azureSubscription: $(suscription)
          resourceGroupName: $(RG)
          location: $(Location)
          csmFile: '$(System.DefaultWorkingDirectory)/_jmartinperalta_crud/mysql/template.json'
          csmParametersFile: '$(System.DefaultWorkingDirectory)/_jmartinperalta_crud/mysql/parameters.json'

      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            New-AzResourceGroupDeployment -ResourceGroupName $(RG) `
              -TemplateUri https://raw.githubusercontent.com/jmartinperalta/crud/master/WebApp/template.json `
              -TemplateParameterUri https://raw.githubusercontent.com/jmartinperalta/crud/master/WebApp/parameters.json